version: 2.0.{build}
branches:
  only:
    - master
image: Visual Studio 2022
configuration: Release
platform: Any CPU
before_build:
  - cmd: nuget restore
build:
  verbosity: minimal
test:
  categories:
    only:
      - Unit
artifacts:
  - path: '**\*.nupkg'
deploy:
  - provider: NuGet
    api_key:
      secure: 898R9mUNx5qb48RpaxNn7Qntf7uc+tNKX3RAA6h4iiKfzZODXONqyhUDyJo4p386
    skip_symbols: true
    artifact: /.*\.nupkg/