version: 3.0.{build}
image: Visual Studio 2022
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
branches:
  only:
    - master
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
test:
  categories:
    only:
    - Unit
deploy:
- provider: NuGet
  api_key:
    secure: 898R9mUNx5qb48RpaxNn7Qntf7uc+tNKX3RAA6h4iiKfzZODXONqyhUDyJo4p386